### ISSUE TITLE
Question regarding snapshot

### ISSUE THREAD

**Issue by OwenVey** [taycaldwell/riot-api-java#102]
Is there a way I could get a snapshot .jar file of the head branch so that I can start using Riot's V3 APIs until you guys release 4.0? Thanks.

**Comment by Linnun** [comment]
I have created a snapshot of the current master branch *as is*: http://temp.linnun.net/riot-api-java.jar

Please note that this is a link to a temporary file. I will not maintain the linked file or guarantee that it will be available forever.
