### ISSUE TITLE
AsyncExample's call to getSummoner fails on cast to Map<String, Summoner>

### ISSUE THREAD

**Issue by ryanhaveson** [taycaldwell/riot-api-java#103]
Hi there.  I am running the sample code "AsyncExample".

When request.getDto() is called in the onRequestSucceded call from apiAsync.getSummoner, it is failing to be cast to a Map<String, Summoner> as it is expecting type class.Summoner.  This results in a ClassCastException.

--Ryan

**Comment by Linnun** [comment]
Looks like we forgot to update that example for the v3 Api changes. This has been fixed now: https://github.com/taycaldwell/riot-api-java/commit/b7a3927e066513508a5723a3f235a51943e25acc

Thanks!

**Comment by ryanhaveson** [comment]
With this fix, the compiler spews an error:

Error:(43, 33) java: local variable eSummoner is accessed from within inner class; needs to be declared final.

I never knew that rule.  Not sure if it is only some compilers that enforce this.  Seems like it would be better as a warning not an error...

--Ryan
--Ryan
