### ISSUE TITLE
 LeagueAPI uses  Endpoint league-V2.5, instead of League-V3

### ISSUE THREAD

**Issue by Nickypoo** [taycaldwell/riot-api-java#106]
It's stated that it uses League-V3, but on the source code here 
![f008c1c0b0425649ac952d4d28dfedfa](https://user-images.githubusercontent.com/29789216/27719317-8ac78dd8-5d1f-11e7-9fd5-75f438e854ee.png)

it's clearly using the endpoint League v2.5 which is going to be depreciated.

**Comment by taycaldwell** [comment]
https://github.com/taycaldwell/riot-api-java/tree/master/src/main/java/net/rithms/riot/api/endpoints/league/methods
