### ISSUE TITLE
getting Match from MatchList

### ISSUE THREAD

**Issue by acmahalkasi** [taycaldwell/riot-api-java#112]
Hello,

I think there is a problem to getting match by matchId from API. Here is my code;

```
MatchList matchList = api.getRecentMatchListByAccountId(Platform.TR, accountId);
for (MatchReference matchReference : matchList.getMatches()) {
                net.rithms.riot.api.endpoints.match.dto.Match match = api.
                        getMatch(Platform.TR, matchReference.getGameId(), summonerId);
....
}
```

and the match object is returning null.

Does anyone have an idea about it?

**Comment by taycaldwell** [comment]
Although this shouldn't be resulting in the issue you are having I will point it out anyways.
You are passing in a summonerId when the method expects an accountId.

```java
public Match getMatch(@NotNull Platform platform,
                      long matchId,
                      long forAccountId)
              throws RiotApiException

Parameters:
platform - Platform to execute the method call against.
matchId - The ID of the match.
forAccountId - If provided, used to identify the participant to be unobfuscated.
```

As for receiving a null match - can you please provide the library version number you are currently using, and the summoner? I am unable to replicate this issue.

**Comment by taycaldwell** [comment]
Hi @acmahalkasi,

Unfortunately, your issue cannot be reproduced and we have not received any of the additional information regarding this from you.

This issue will now be closed. Feel free to reopen it if you find yourself still running into any troubles regarding your problem.

Thanks.
