### ISSUE TITLE
RankedStats missing?

### ISSUE THREAD

**Issue by GwFreak01** [taycaldwell/riot-api-java#114]
Hi, sorry I'm new to this, but does getRankedStats() still work? It says I am missing "net.rithms.riot.dto.Stats.RankedStats"

**Comment by taycaldwell** [comment]
Over the past few months, Riot announced the [Riot Games API v3](https://discussion.developer.riotgames.com/articles/652/riot-games-api-v3.html). All v1/v2 endpoints were deprecated and recently removed. Unfortunately the stats endpoint backing this method was completely removed and not replaced with a v3 endpoint.

Please read the article above for details on why Riot has made the decision to not replace this endpoint.
