### ISSUE TITLE
Guidance in getting wins ?

### ISSUE THREAD

**Issue by ccancin0** [taycaldwell/riot-api-java#116]
Not sure if I am calling the right methods here:

import net.rithms.riot.api.endpoints.league.dto.LeagueList;

Summoner summoner = api.getSummonerByName(Platform.NA, username);
Set<LeaguePosition> league = api.getLeaguePositionsBySummonerId(Platform.NA, summoner.getId());

Now after this if I'm correct so far to get wins would if be like this:
int wins = league.getWins();

Because league**.** doesn't give me those methods. Using newest version 4.0.1

**Comment by Linnun** [comment]
Note that `league` is a `Set`.

You can iterate over it like this:

`
import net.rithms.riot.api.endpoints.league.dto.LeagueList;

Summoner summoner = api.getSummonerByName(Platform.NA, username);
Set<LeaguePosition> leagues = api.getLeaguePositionsBySummonerId(Platform.NA, summoner.getId());

for(LeaguePosition league : leagues){
   int wins = league.getWins();
}
`

Note that this iterates over all your leagues. If you want wins for a specific league, you could go like this:

`
import net.rithms.riot.api.endpoints.league.dto.LeagueList;

Summoner summoner = api.getSummonerByName(Platform.NA, username);
Set<LeaguePosition> leagues = api.getLeaguePositionsBySummonerId(Platform.NA, summoner.getId());

int wins = 0;
for(LeaguePosition league : leagues){
   if(league.getQueueType().equalsIgnoreCase("RANKED_SOLO_5x5")){
      int wins = league.getWins();
      break;
   }
}
`

**Comment by ccancin0** [comment]
Thanks!
