### ISSUE TITLE
RateLimit issue

### ISSUE THREAD

**Issue by splitzyo** [taycaldwell/riot-api-java#121]
Hi, I ve been using this library to get different informations from League of Legends API and when I do, I get:
> RateLimitException: Rate limit exceeded 

What is the proper way to handle the rate limit and get 100 % of it ?

**Comment by Linnun** [comment]
The DefaultRateLimitHandler of this library only handles rate limits after it is too late. So basically if you already got a 429 response from the Riot Api, it will try to respect the Retry-After header for the given service, method or app.

There is also a BufferedRateLimitHandler in the current version of this library that, when configured properly, will try to prevent 429 responses by stopping to fire new requests early. Basically what it does is after a request it reads the rate limit headers from the Riot Api's response, and if the current usage is above X%, it will issue a manual X second cooldown on making requests to the given endpoint(s).

In a later version we also want to provide an AtomicRateLimitHandler (currently WIP) that tries to properly keep track of your rate limits by counting the requests you make and stopping a request when it would exceed the rate limit.

You can also write your own rate limiting logic by implementing the RateLimitHandler interface or extending the DefaultRateLimitHandler class. To use a non-default RateLimitHandler, use the #setRateLimitHandler() method of your ApiConfig.


In any case, regardless of if the Riot Api throws a 'real' RateLimitException or if the RateLimitHandler of your choice prevents making a call (in which case it will throw a RespectedRateLimitException, which inherits RateLimitException), your request will fail and you will not get a response from it. What you can do is catch RateLimitException when you do a request. On that RateLimitException object you can call #getRetryAfter() which will give you an integer that is the amount of seconds you need to wait before you can fire the request again.
It depends on the specific application if your best choice would be to sleep and retry the request, or drop it entirely.
