### ISSUE TITLE
Converting an image from net.rithms.riot.api.endpoints.static_data.dto.Image to java.awt.image

### ISSUE THREAD

**Issue by GazzLightyear** [taycaldwell/riot-api-java#125]
Good evening.
I state I'm not an espert developer and I have a basic knowledge about Image class. 
After some research I didn't find a way to convert an image received from Champion or ChampionSpell class through getImage() method or from Spell class. Is it possible? I'm actually doing a projext for school that describe champion's features and I would set these images in some labels. Is using Data Dragon the only way to get a "normal" image (jpg,png,etc.)?

Thanks everyone for help :D

**Comment by laazer** [comment]
It's been awhile since I've looked at this api but if I remember correctly, you have to download all the images from riot directly in a zip file. The fields from the image class correspond to the image properties.

**Comment by GazzLightyear** [comment]
ah ok, thank you! Do you know the link to download all images?

**Comment by laazer** [comment]
https://developer.riotgames.com/static-data.html

**Comment by taycaldwell** [comment]
Hi @GazzLightyear,

The image field names correspond to image resources found on DDragon. You can either use the CDN to access these images, as described in the [documentation](https://developer.riotgames.com/static-data.html) @laazer provided, or alternatively download a tar ball with all the image files and include them in your project. The tar ball can be found [here].(https://ddragon.leagueoflegends.com/cdn/dragontail-8.3.1.tgz).

**Comment by GazzLightyear** [comment]
Thank you!!! This is a very good news :D now I can finally finish my
project. Thank you again ;D

Il ven 16 feb 2018 23:13 Taylor Caldwell <notifications@github.com> ha
scritto:

**Comment by taycaldwell** [comment]
No problem. Stay gucci.
