### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by JessWalters** [taycaldwell/riot-api-java#126]
Can you add a new Release. I would really like to utilize the Verification endpoint. I noticed it is pushed but not released yet, thanks.

**Comment by taycaldwell** [comment]
Hi @JessWalters,

A new release will be made Soon™ with these changes.

In the meantime, feel free to build from the source.

Thanks.

**Comment by taycaldwell** [comment]
Release 4.1.0 is now live: https://github.com/taycaldwell/riot-api-java/releases/tag/4.1.0
