### ISSUE TITLE
Runes Reforged API Call

### ISSUE THREAD

**Issue by benthecarman** [taycaldwell/riot-api-java#129]
When will support for runes reforged be added?

**Comment by CodyBontecou** [comment]
I'm curious if this is still the case? If there's currently development occurring, I'd be happy to spend some time implementing it.

**Comment by lsinquin** [comment]
Any update on this issue?

**Comment by taycaldwell** [comment]
PR for Runes Reforged changes: https://github.com/taycaldwell/riot-api-java/pull/137

**Comment by taycaldwell** [comment]
Now released in 4.1.0: https://github.com/taycaldwell/riot-api-java/releases/tag/4.1.0
