### ISSUE TITLE
problem in the api instance

### ISSUE THREAD

**Issue by pams95** [taycaldwell/riot-api-java#135]
Hi,
I have an error when i want to instanciate the api with my key : 

the error code : https://hastebin.com/osaxemutem.txt

the code who gives me problems : `ApiConfig config = new ApiConfig().setKey("****");`

I use Eclipse and the API is installed by maven.

thanks to help me ! 
pams_95

**Comment by taycaldwell** [comment]
Post the contents of your pom.xml file please.

**Comment by pams95** [comment]
Sorry I am new with maven : 
POM.xml : https://hastebin.com/abuxiwirus.xml

**Comment by pams95** [comment]
@taycaldwell did u see my response

**Comment by taycaldwell** [comment]
The pom file is fine. Your classpath is obvi fucked up, but it's hard to help diagnose the issue without knowing how you are running the project. How are you running the project? Can you provide your Classpath?

If you're using an IDE try cleaning your project.

You also don't need to declare Gson as a dependency unless you need that specific version for something else.

**Comment by pams95** [comment]
Ok so I need to clean my project. I will reply later to say if it’s good.
THX a lot !
Pams

**Comment by pams95** [comment]
1
