### ISSUE TITLE
LeaguebySummonerID : 403: Forbidden 

### ISSUE THREAD

**Issue by Tobias3107** [taycaldwell/riot-api-java#136]
Hey i try to get the Rank about Summerners and Write this

		String RiotKey = null;
		ApiConfig cfg = null;
		RiotApi api = null;
	public Ranked(String RiotKeya) {
		RiotKey = RiotKeya;
		cfg = new ApiConfig();
		cfg.setKey(RiotKey);
		cfg.setAsyncRequestTimeout(20);
		api = new RiotApi(cfg);
		
	}

	private long getSummerIdUser(Platform Region, String SummerName) {
		if(api != null) {
			try {
				Summoner s = api.getSummonerByName(Region, SummerName);
				System.out.println(s.getName());
				System.out.println(s.getSummonerLevel());
				System.out.println(s.getId());
				System.out.println(s.getAccountId());
				return s.getId();
			} catch (RiotApiException e) {
				e.printStackTrace();
				System.err.println("SummonerID - FALSE Region Or SummonerName");
			}
		}
		return -1;
	}

	public void getSoloDouQ(Platform Region, String SummonerName) {
		if(api != null) {
			try {
				List<LeagueList> g = api.getLeagueBySummonerId(Region, getSummerIdUser(Region, SummonerName));
				for(int i =0; i<g.size();i++) {
					System.out.println(i + " = " +g.get(i));
				}
			} catch (RiotApiException e) {
				e.printStackTrace();
				System.err.println("FALSE Region Or SummonerID");
			}
		}
	}

	public void getFlex() {
		if(api != null) {
			
		}
	}
}

When i start my Progamm then comes an Error This : 

`net.rithms.riot.api.RiotApiException: 403: Forbidden
	at net.rithms.riot.api.request.Request.execute(Request.java:176)
	at net.rithms.riot.api.request.Request.<init>(Request.java:94)
	at net.rithms.riot.api.EndpointManager.callMethodAndReturnDto(EndpointManager.java:52)
	at net.rithms.riot.api.RiotApi.getLeagueBySummonerId(RiotApi.java:1200)
	at de.tobi.Riot_TS_Website.API.RIOT.Ranked.getSoloDouQ(Ranked.java:44)
	at de.tobi.Riot_TS_Website.API.RIOT.TobiRiotApi.f(TobiRiotApi.java:15)
	at de.tobi.Riot_TS_Website.App.main(App.java:15)
FALSE Region Or SummonerID`

I test my Key with the MatchListExaple from this Site and it works. I regenerate my Api key but it doesnt work 
I test also the Async Example and it work. Musst i work with Async or can i also the Sync and when i should use the Async?

**Comment by pams95** [comment]
Hello guys,
i have the same issue with the riot api, is anybody who can help us ?
i know that the 403 error come when we are blacklisted but I am new with riot api and my key is again validate.

pams_

**Comment by jluzonpr** [comment]
Are you using a Dev key? Have you regenerated it?

**Comment by taycaldwell** [comment]
This is just happening because the library uses an old endpoint. 

I'll update it. :^)

**Comment by taycaldwell** [comment]
Updated endpoint available in new 4.1.0 release. Please update.
https://github.com/taycaldwell/riot-api-java/releases/tag/4.1.0
