### ISSUE TITLE
 get Summoner ID in champ select

### ISSUE THREAD

**Issue by boaralex2000** [taycaldwell/riot-api-java#144]
Hi, I was wondering if there is a way to get the summoner ID of the players currently in your champ selection. I am trying to make a program where I can add summoner IDs manually to an array list and when i run the program it will alert me if a player in my lobby (my team ONLY) matches a player on the list. This program is intended to be used as a way to blacklist people you don't like playing with due to toxic behavior, afking, inting, etc. You'd then be able to just dodge the current queue if you don't feel like playing with the same person that griefed your previous games.

**Comment by Linnun** [comment]
The Riot Api has no way of receiving any champion select data. For this you will need to use the LCU API. Please note that Riot enforces a couple special rules for using the LCU API. You can read more about it here: https://developer.riotgames.com/league-client-apis.html
