### ISSUE TITLE
Endpoints for V4 not updated

### ISSUE THREAD

**Issue by BradyNas** [taycaldwell/riot-api-java#146]
The api call url for get match by match id and get summoner by summoner name still use the V3 endpoints. It seems like this is happening for other endpoints as well. This issue is happening both when I download riot-api-java as a .jar and as a maven dependency. is there any way to resolve this either on your end or on my end? Any feedback would be greatly appreciated.

**Comment by Linnun** [comment]
I have just pushed a new release which supports the new v4 endpoints. Please find the latest release here: https://github.com/taycaldwell/riot-api-java/releases

Please note that I have no clue how maven works and don't maintain it, so make sure to download the jar manually for now until Taylor gets around to update the maven build.

**Comment by BradyNas** [comment]
Thank you so much. You are a beast!
