### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by 01Parzival10** [taycaldwell/riot-api-java#156]
I'm completly new so maybe I'm just an Idoit. But when i try to:

try {
                Summoner summoner = api.getSummonerByName(Platform.EUW, args[2]);
                channel.sendMessage("Name: " + summoner.getName()).queue();
                channel.sendMessage("Summoner Level: " + summoner.getSummonerLevel()).queue();

                Set<LeaguePosition> leagues = api.getLeaguePositionsBySummonerId(Platform.EUW, summoner.getId());
                for (LeaguePosition league : leagues) {
                    channel.sendMessage(league.getLeagueName() + ": " + league.getRank() + " " + league.getLeaguePoints()).queue();
                }

            } catch (RiotApiException e) {
                e.printStackTrace();
                return;
            }`

I get following Error: 

net.rithms.riot.api.RiotApiException: 403: Forbidden
	at net.rithms.riot.api.request.Request.execute(Request.java:181)
	at net.rithms.riot.api.request.Request.<init>(Request.java:94)
	at net.rithms.riot.api.EndpointManager.callMethodAndReturnDto(EndpointManager.java:52)
	at net.rithms.riot.api.RiotApi.getLeaguePositionsBySummonerId(RiotApi.java:1557)
	at Commands.RitoTest.performCommand(RitoTest.java:34)

I renewed my DevKey so this shouldn't be a problem.

**Comment by Nauschi** [comment]
Hi,

seems like the endpoint that's used by _GetLeaguePositionsBySummonerId.java_ is outdated.

Go to _GetLeaguePositionsBySummonerId.java_ and change the urlBase from "/lol/league/v4/positions/by-summoner/" to "/lol/league/v4/entries/by-summoner/

**Comment by 01Parzival10** [comment]
Thank you.
I was using Version 4.2 thats prob. what was wrong
