### ISSUE TITLE
Validating summoner names

### ISSUE THREAD

**Issue by taycaldwell** [taycaldwell/riot-api-java#75]
So, there is [a thread about validating API calls](https://developer.riotgames.com/discussion/announcements/show/6XNUo1LP) on the forums.

Most of the stuff discussed, like using the proper DNS for a region and correct platform ID names, the library already enforces.

The one thing we don't really do is validate summoner names before making an API call.

> If you have a input field on your site or in your app that lets a user enter a summoner name to lookup, do not blindly pass that value along to the API without first doing some validation. Any request with a name parameter that contains any characters that are not valid for a summoner name, even if they are URL encoded, will return a 403. The full set of allowed characters across Riot, Tencent, and Garena regions includes any visible Unicode letter characters, digits (0-9), spaces, underscores, and periods. Other than that, no punctuation characters are allowed. Thus, the regular expression to use for validating summoner names would be "^[0-9\p{L} _.]+$". You should be rejecting inputs that don't match this regular expression (i.e., that contain any punctuation characters other than periods, underscores, and spaces), rather than sending them to the API.

This change should be as simple as just running summoner names through the regular expression provided. I'm just opening this issue till I get around to doing it.

**Comment by Linnun** [comment]
When implementing, please make sure to test this with all kinds of characters before committing (at minimum: latin, japanese, korean, russian)

**Comment by taycaldwell** [comment]
Closing this issue. For explanation, see discussion for https://github.com/taycaldwell/riot-api-java/pull/120
