### ISSUE TITLE
API request counter (enhancement idea)

### ISSUE THREAD

**Issue by briceambrosiak** [taycaldwell/riot-api-java#76]
Just thinking, I'm often reaching the API limit with the new app I'm developing. I would think it could be useful, for debug at least, to have metrics about the usage of the API.

I know some API doesn't consume an API call on your account (like static data) and others does. We could have an history in the library allowing the developer to see which methods are called the most and consume the maximum of calls.

It could be a queue emptying the oldest request made. It would of course be activable or not to not consume an overhead of memory if not desired.

**Comment by taycaldwell** [comment]
Outside of exposing the `X-Rate-Limit-Count` header included in the API response, I have no intention to implement metrics of API usage to the library.

The goal of `riot-api-java` is to simply serve as a wrapper around the Riot Games API.

If you would like to continue discussion on how we could implement features to better improve rate-limit handling and throttling, please reference the currently open issue: https://github.com/taycaldwell/riot-api-java/issues/77
