### ISSUE TITLE
Ranked Teams deprecation

### ISSUE THREAD

**Issue by taycaldwell** [taycaldwell/riot-api-java#80]
Ranked teams are planned to be deprecated by early December. With this, the following endpoints will be removed from the Riot Games API:

**league-v2.5**
_/api/lol/{region}/v2.5/league/by-team/{teamIds}
/api/lol/{region}/v2.5/league/by-team/{teamIds}/entry_

**team-v2.4**
_/api/lol/{region}/v2.4/team/by-summoner/{summonerIds}
/api/lol/{region}/v2.4/team/{teamIds}_

This issue is to prepare for these API changes come early December.

**Comment by rithms** [comment]
Official announcement related to this task:
https://developer.riotgames.com/discussion/announcements/show/ar0Z6Ery

**Comment by rithms** [comment]
Note this issue can be worked before these changes are made, but will not be merged until the endpoints are officially removed.

**Comment by taycaldwell** [comment]
Classes and methods for Team related endpoints have now been removed. https://github.com/taycaldwell/riot-api-java/commit/ffbd83ed4f4da27e46cd7e056c0d0132be85578c https://github.com/taycaldwell/riot-api-java/commit/9e83d4b93f26560968c68c5b8e5d5c8bdf6be81a https://github.com/taycaldwell/riot-api-java/commit/18ad3e543a620b614ee9bda43ee73ff080615a5c
