### ISSUE TITLE
Tests should not depend on the status of the API

### ISSUE THREAD

**Issue by jfisher446** [taycaldwell/riot-api-java#81]
Tests are currently connecting to the actual Riot API in order to retrieve data. This dependency should be broken and the API should be mocked so that only this project's code is being tested.

Consequently, the API Key and Tournament API Key can then be removed from the RiotApiTest class.

**Comment by rithms** [comment]
Agreed. For unit tests this should be mocked.

Thanks for pointing this out.

**Comment by jfisher446** [comment]
I'm currently toying with this with this for self development, but not enough to commit to a PR. If I get there, I'll submit.

**Comment by rithms** [comment]
Sounds good. Feedback and PRs are always very much appreciated.

**Comment by LogicalOverflow** [comment]
Another problem that came up while building with tests on is, that Tryndamere changed his summoner name.

**Comment by taycaldwell** [comment]
K, I'll update it to use the summoner name "LoveMeSomeRegi".

Thanks for the heads up.

**Comment by taycaldwell** [comment]
https://github.com/taycaldwell/riot-api-java/issues/83 has been updated to include the remaining work needed for this task.
