### ISSUE TITLE
[Question] Java Doc Update?

### ISSUE THREAD

**Issue by ngwangsa** [taycaldwell/riot-api-java#84]
The Java doc for the API is down. Wanted to see if you're just updating it at the moment or if something else was up. 
![javadoc](https://cloud.githubusercontent.com/assets/14826491/21528939/fc513258-ccea-11e6-8d5b-8f9b0583dc4f.png)

**Comment by taycaldwell** [comment]
The link to the Javadoc was changed. I have reflected this change in the README.

Sorry for the inconvenience.

**Comment by ngwangsa** [comment]
Thanks for all your work!
