### ISSUE TITLE
Got 0 loses ?

### ISSUE THREAD

**Issue by manercraft** [taycaldwell/riot-api-java#85]
I would like to test the API and I got 0 lost on my account, Wut ?
![eclipse_2016-12-29_02-53-53](https://cloud.githubusercontent.com/assets/1338257/21535203/1502bf7e-cd72-11e6-83e9-f1912f16df64.jpg)

**Comment by taycaldwell** [comment]
Similar to the game client, the player stat summary endpoint will only show losses for ranked queues. 0 losses in this case means the value was not returned by the API. 

¯\_(ツ)_/¯

**Comment by manercraft** [comment]
I have less than 100 games in a ranked, so I can not have 725 wins in ranked oO

**Comment by taycaldwell** [comment]
Your queue seems to add the wins from all queues returned by the player stat summary endpoint, not just ranked queues.

Check the playerStatSummaryType field.

**Comment by manercraft** [comment]
Hum, OK, thank for the information

**Comment by taycaldwell** [comment]
np.

**Comment by manercraft** [comment]
Other question,
How get name of champion by ID
Name of queue by queueID
Name of Map by MapID
etc ? :D

**Comment by taycaldwell** [comment]
To get item, champion, or spell data by their IDs, you need to use the static data endpoints.

The methods for these endpoints start with getData...

For example, you can get data for a champion (including their name) by calling the method getDataChampion(), and passing in the champion ID as a parameter.

queue types, game modes, and maps however are all game constants, and can be accessed using an enum.

You can find those [here.](https://github.com/taycaldwell/riot-api-java/tree/master/src/main/java/net/rithms/riot/constant)
