### ISSUE TITLE
API and Jsps

### ISSUE THREAD

**Issue by ChristopherMcKenzie** [taycaldwell/riot-api-java#87]
Is it possible to use this along with JSPs in a Maven project?

I've been trying but it doesn't seem to be working.

**Comment by taycaldwell** [comment]
Can you elaborate, and verify that your issue isn't related to the already open issue https://github.com/taycaldwell/riot-api-java/issues/61?

Thanks.

**Comment by ChristopherMcKenzie** [comment]
Its not but I did find a work around for myself, thanks
