### ISSUE TITLE
Riot Games API v3: Update region-based domains to platform-based domains.

### ISSUE THREAD

**Issue by taycaldwell** [taycaldwell/riot-api-java#90]
In conjunction with with the new endpoint standardization, the API is switching to platform-based domains to determine where to route incoming requests.

Current:

```
https://na.api.pvp.net
```

Future:

```
https://na1.api.riotgames.com
```

As these changes roll out, all appropriate domains should be updated to be platform-based rather than region-based.

Full mapping of regions and platforms can be found on the [Regional Enpoint](https://developer.riotgames.com/regional-endpoints.html) documentation page.

**Acceptance Criteria:**
Domains are updated to be platform-based.

**Comment by Linnun** [comment]
This will basically be done automatically for all methods that are converted to v3 by using a Platform instead of a Region as parameter. See https://github.com/taycaldwell/riot-api-java/commit/f397ff2a89c0628428eed7d5afd3a2ce92567adc
