### ISSUE TITLE
Riot Games API v3: Update methods with account ID parameters.

### ISSUE THREAD

**Issue by taycaldwell** [taycaldwell/riot-api-java#91]
As the Riot Games API v3 changes are rolled out, endpoints will be updated to use account IDs rather than summoner ID.

These endpoints need to be updated accordingly.

**Acceptance Criteria:**
All endpoints utilizing new account ID query parameters are updated to support account IDs.

**Comment by Linnun** [comment]
This only affects methods in the new Riot Api v3, thus we don't need to change anything specifically for this. Just converting our methods to the v3 APIs as soon as they get available should do the trick.
