### ISSUE TITLE
Riot Games API v3: Deprecation of stats-v1.3

### ISSUE THREAD

**Issue by taycaldwell** [taycaldwell/riot-api-java#92]
The *stats-v1.3* endpoint will be deprecated with the new Riot Games API v3 updates.

Because there will be no replacement for this endpoint, all methods utilizing it should be removed.

**Acceptance Criteria:**
All methods and support for stats-v1.3 is removed.

**Comment by Linnun** [comment]
Done as part of https://github.com/taycaldwell/riot-api-java/commit/f397ff2a89c0628428eed7d5afd3a2ce92567adc
