### ISSUE TITLE
How to integrate with android?

### ISSUE THREAD

**Issue by bensinjin** [taycaldwell/riot-api-java#94]
I've tried multiple versions of this api but I cant get it integrated into my android app. I keep getting:

`Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.`

and have tried most posted solutions to no avail - this is using tag 3.8.2 as I wasn't able to get 3.9.0 working either - I have also tried the 3.8.2-android tag and get the same error. Sorry new to Android dev just wondering if there was a solution kickin around for me? I'm using Android Studio 2.3.1.

**Comment by taycaldwell** [comment]
What version of Java are you using?

Please note, using this library for Android development is no longer encouraged, as it caters to bad security practices.

**Comment by taycaldwell** [comment]
In addition to this, Riot Games has announced a [90 day deprecation period](https://discussion.developer.riotgames.com/articles/1053/v1v2-90-day-deprecation-period-has-begun.html) in which all old endpoints utilized by the older versions of this library will no longer be supported.

In other words, as odd as it seems - I'm encouraging you not to use the library for Android development, and stay away from older versions if you plan to take it server-side.

**Comment by bensinjin** [comment]
Oh ok thx for your response - I guess I'll write my own little wrapper, cheers!

**Comment by taycaldwell** [comment]
Very much encouraged! Sorry for the buzz kill.
