### ISSUE TITLE
Riot Api v3 - Missing tournament methods

### ISSUE THREAD

**Issue by Linnun** [taycaldwell/riot-api-java#95]
I currently have no access to a tournament key, thus I also don't see the documentation to those endpoints and methods in the Riot Api.

@taycaldwell Can you create a group for this project on the Riot Developer page,  add me to that group, and request a tournament key for the purpose of creating this library, so we can see the tournament endpoints in the documentation?

Alternatively, if you already have access to a tournament key, can you screenshot the entire documentation of all tournament related endpoints and methods? This probably includes the services TOURNAMENT-V3, TOURNAMENT-STUB-V3 and some methods in MATCH-V3.

**Comment by taycaldwell** [comment]
Hey Linunn,

I have created a group on the dev portal and I'm working on getting you added to it as well.
I have sent in an application for access to the tournament endpoints so we can properly test the methods when we update the library.

I believe the documentation for these endpoints is publicly visible if you are logged out of your dev portal account, however when you sign in it is hidden unless you have access. I still however, would like to get a key for purposes of further developing this library.

I will let you know when you are added to the group.

As always, I greatly appreciate your help on this project!

- rithms

**Comment by taycaldwell** [comment]
You are now added to the riot-api-java group on the Dev portal, and the project has been approved for a key to test the tournament API methods.
