### ISSUE TITLE
Simple Idea to help avoid off by one/index errors.

### ISSUE THREAD

**Issue by JumpingRock** [taycaldwell/riot-api-java#96]
An idea for improvement. Could I submit a Pull request to add a function the Match.java Dto: `getParticipantByParticipantID(long participantID){...}`

I'm a bit new to the open source game. So I understand if you want everything standardized in your classes, but I think this function could improve things just a little bit. 

ParticipantIDs are from 1-10 and Lists are obviously indexed 0-9.
So we could use the above function instead of a simple .get(). A .get() from the list makes us correct the index which is bulky.

## What happened to me:
Using the old API, v3.8.2, I attempted this call:
`ParticipantStats stats = api.getMatch(matchID).getParticipants().get(participantID).getStats();`

The result was an "Index out of bounds error".
This part failed: `getParticipants().get(participantID)`
To correct it I have to do `getParticipants().get(participantID-1)`

Note: I ran into this because of 3x3 ranked history. My participantID was 6, but the List index is 0-5. I did not realize I was getting the wrong participant before.

**Comment by Linnun** [comment]
I like the idea of providing a little utility method like that. I'll have a look at this later today.

**Comment by taycaldwell** [comment]
There's definitely many things that could be improved and utility methods that could be added to make the data returned from the API easier to work with after the JSON has been converted. 

Having to pass in `participantID-1` is understandable, as you're dealing with indices of a list, not keys and values. However, I do think having a utility method to easily grab participants by their ID is a good suggestion and more correct, as there's nothing guaranteeing that the indices of the participants will always be equal to `particpant-1`. `1` in this case just seems like some magic number bullshit that could change tomorrow if Riot updates participant IDs to be something other than `1-10`.

**Comment by Linnun** [comment]
I have added a few utility methods like the one you suggested in https://github.com/taycaldwell/riot-api-java/commit/2cc8fa2609f83f5622761d624ee320f4fb004c43 -- These will be part of the 4.0.0 release.

If you have more ideas for improvements of any kind, please let us know!

**Comment by JumpingRock** [comment]
Awesome that is great to see, I appreciate it! Yeah I've been working heavily with the wrapper, so I'll be in touch if I ideas.
