### ISSUE TITLE
Get current Solo Queue 5v5 rank - JAVA Riot API

### ISSUE THREAD

**Issue by Vodkamir** [taycaldwell/riot-api-java#97]
Hello, I have been using taycaldwell Riot-Api Code of getting the current solo Q 5v5 rank with the following code

    ApiConfig config = new ApiConfig().setKey("Key");
	RiotApi api = new RiotApi(config);
		String username = JOptionPane.showInputDialog("Enter Summoner 
    name").toLowerCase().replace(" ", "");

	net.rithms.riot.api.endpoints.summoner.dto.Summoner summoner = 
    api.getSummonerByName(Platform.EUW, username);

    List<League> leagues = api.getLeagueEntryBySummoner(summoner.getId());
    
    for(League league : leagues) {
    	
        if(league.getQueue().equals(QueueType.RANKED_SOLO_5x5.name())) {
            System.out.println("League Name: " + league.getName());
            System.out.println("Tier: " + league.getTier());

      
            LeagueEntry entry = league.getEntries().get(0);
            System.out.println("Division: " + entry.getDivision());
            System.out.println("LP: " + entry.getLeaguePoints());
            System.out.println("Wins: " + entry.getWins());
            System.out.println("Losses: " + entry.getLosses());

However when do I run it gives me an error :Exception in thread "main" java.lang.NullPointerException
indicating the line :   for(League league : leagues) {

**Comment by taycaldwell** [comment]
Can you provide the stack trace?

**Comment by Vodkamir** [comment]
Not sure how to for this one, Im quite new to this (really sorry)

**Comment by dschow** [comment]
Should should check to see if `leagues` is null before trying to iterate over it.

**Comment by Vodkamir** [comment]
Thread [main] (Suspended (e xception NullPointerException))	
	Test2.main(String[]) line: 59 ---->(for(League league : leagues) {) statement

**Comment by taycaldwell** [comment]
What @dschow said. Check that the collection isn't null before you iterate over it.

I'm wondering if it we should utilize Optionals for return values to enforce devs to check if data #isPresent before they handle it. Thoughts @Linnun?

**Comment by Vodkamir** [comment]
Tried to check if the leagues is null gave me a response that Can only iterate over an array or an instance of java.lang.Iterable

**Comment by taycaldwell** [comment]
Can you provide your imports?

**Comment by Vodkamir** [comment]
Some of them I have used for other requests that had the similar issue

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import net.rithms.riot.api.ApiConfig;
import net.rithms.riot.api.RiotApi;
import net.rithms.riot.api.RiotApiException;
import net.rithms.riot.api.endpoints.champion.dto.Champion;
import net.rithms.riot.api.endpoints.stats.dto.AggregatedStats;
import net.rithms.riot.api.endpoints.stats.dto.PlayerStatsSummaryList;
import net.rithms.riot.api.endpoints.stats.dto.RankedStats;
import net.rithms.riot.constant.Platform;
import net.rithms.riot.constant.QueueType;
import net.rithms.riot.constant.Region;
import net.rithms.riot.constant.Season;
import net.rithms.riot.dto.Champion.ChampionList;
import net.rithms.riot.dto.League.League;
import net.rithms.riot.dto.League.LeagueEntry;
import net.rithms.riot.dto.Stats.ChampionStats;
import net.rithms.riot.dto.Stats.PlayerStatsSummary;
import net.rithms.riot.dto.Summoner.Summoner;
import net.rithms.riot.api.endpoints.stats.dto.AggregatedStats;

**Comment by taycaldwell** [comment]
Okay... Looks fine so far - 
Can you provide your updated code?

**Comment by Vodkamir** [comment]
I left it as it is

net.rithms.riot.api.endpoints.summoner.dto.Summoner summoner = api.getSummonerByName(Platform.EUW, username);
    List<League> leagues = api.getLeagueEntryBySummoner(summoner.getId());
    
    for(League league : leagues) {
    	
        if(league.getQueue().equals(QueueType.RANKED_SOLO_5x5.name())) {
        	
            System.out.println("League Name: " + league.getName());
            System.out.println("Tier: " + league.getTier());
            LeagueEntry entry = league.getEntries().get(0);
            System.out.println("Division: " + entry.getDivision());
            System.out.println("LP: " + entry.getLeaguePoints());
            System.out.println("Wins: " + entry.getWins());
            System.out.println("Losses: " + entry.getLosses());

**Comment by taycaldwell** [comment]
and doing this gives you the compiler error? 🤔 :

```java
if (leagues != null) {
    for (League league : leagues) {
        if (league.getQueue().equals(QueueType.RANKED_SOLO_5x5.name())) {
            System.out.println("League Name: " + league.getName());
            System.out.println("Tier: " + league.getTier());
            LeagueEntry entry = league.getEntries().get(0);
            System.out.println("Division: " + entry.getDivision());
            System.out.println("LP: " + entry.getLeaguePoints());
            System.out.println("Wins: " + entry.getWins());
            System.out.println("Losses: " + entry.getLosses());
        }
    }
}
```

**Comment by Vodkamir** [comment]
oh for the null code it gives me nothing, a empty console 

 if (leagues != null) {
    
    for(League league : leagues ) {
    	
        if(league.getQueue().equals(QueueType.RANKED_SOLO_5x5.name())) {
        	
            System.out.println("League Name: " + league.getName());
            System.out.println("Tier: " + league.getTier());

            // Get the league entry for the given player of this que
            // and print out the division, lp, and wins and losses
            LeagueEntry entry = league.getEntries().get(0);
            System.out.println("Division: " + entry.getDivision());
            System.out.println("LP: " + entry.getLeaguePoints());
            System.out.println("Wins: " + entry.getWins());
            System.out.println("Losses: " + entry.getLosses());

**Comment by taycaldwell** [comment]
Okay good, no errors.

So the reason you are getting an empty console is because the `leagues` list is `null`, so the print statements are never executed and printed to the console.

Why is the list of leagues `null`?
I believe the API isn't returning league entry data for this summoner, because this summoner isn't ranked.

Can you provide the summoner name you are using so I can verify this for you?

**Comment by Vodkamir** [comment]
Vodkamir Putkin is the name

I have another code to display Played Ranked games with certain champions  including game lost and won which works 
// for(int j= 0; j < championStatsList.size() - 1; j++){
//
//		//Works
//		ChampionStats championStat = championStatsList.get(j); //This  creates a object of championstats that corresponds to the champion at index i in the list championList
//	    net.rithms.riot.dto.Stats.AggregatedStats championStats = championStat.getStats(); //We've created an object of AggregatedStats championStat that contains all the stats of the champion
////	    net.rithms.riot.dto.Static.Champion champ = championList.get(i);
//	  
//	    
//	  
//	   
//	    System.out.println("Champion ID: "+ championStat.getId());
//	    System.out.println("Games Played: " + championStats.getTotalSessionsPlayed());
//	    System.out.println("Wins: " + championStats.getTotalSessionsWon());
//	    System.out.println("Loses: " + championStats.getTotalSessionsLost());
//	    System.out.println("Games Played: " + championStats.getRankedSoloGamesPlayed());

**Comment by taycaldwell** [comment]
What version of the library are you using? >.>

**Comment by Vodkamir** [comment]
I believe the most recent one I believe, 3.9.0

**Comment by Vodkamir** [comment]
Here's the following code which works

RankedStats rankedStats = api.getRankedStats(Region.EUW, null, summoner.getId());

	   net.rithms.riot.dto.Stats.AggregatedStats allChampionsStats = rankedStats.getChampions().get(0).getStats();
//	   PlayerStatsSummaryList summary = api.getPlayerStatsSummary(Region.EUW, summoner.getId());
	
       List<ChampionStats> championList;
       championList = rankedStats.getChampions();
   
       List<ChampionStats> championStatsList;
	    championStatsList = rankedStats.getChampions();
	
	    for(int i=0; i < championList.size() - 1; i++) {
		
//		for(int j= 0; i < championStatsList.size() - 1; j++){
	
		
		ChampionStats championStat = championStatsList.get(i); //This  creates a object of championstats that corresponds to the champion at index i in the list championList
	    net.rithms.riot.dto.Stats.AggregatedStats championStats = championStat.getStats(); //We've created an object of AggregatedStats championStat that contains all the stats of the champion
	
	    System.out.println("Champion ID: "+ championStat.getId());	
	    System.out.println("Games Played: " + championStats.getTotalSessionsPlayed());
	    System.out.println("Wins: " + championStats.getTotalSessionsWon());
	    System.out.println("Loses: " + championStats.getTotalSessionsLost());

**Comment by taycaldwell** [comment]
It looks like there is data being returned for that summoner and queue type by the API for the version of the library you are using, which leads me to believe there is a bug with the library.

I will investigate this further and get back to you.

Sorry for the inconvenience.

**Comment by Vodkamir** [comment]
Thank you very much for the help, much appriciated

**Comment by Linnun** [comment]
It is generally advised that you do NOT use the QueueType enum to check against a league's queueType. The reason is that leagues are not mapped to Queues 1:1. There might be multiple queues that count towards the same league. For example the queues RANKED_SOLO_5x5 and TEAM_BUILDER_RANKED_SOLO both had their games count towards the RANKED_SOLO_5x5 league. Also the name of a league does not have to match the name of any queue at all -- note that *theoretically* Riot could change this in future on short notice.

That being said, you should **always** check the result from an api call for `null`, at least when getting a non-Collection. For Collections, it is admittingly bad practice to have them return as `null` -- they should return empty Collcetions instead. That is something I will look into for the upcoming version 4.0.0 of this api wrapper.

As for your code, other than missing the `null` check it looks fine. My guess would be that the summoner you are looking up is not ranked in any league of the queueType RANKED_SOLO_5x5.

**Comment by Vodkamir** [comment]
Thank you for the help

But the Summoner is ranked, I've tried different names that are ranked for Ranked solo 5x5

This is a one time project that I am using to hand it this week and as general API practice
